/* Generated by 'Generate-Swift-Font-Constants.swift' DO NOT CHANGE */

import UIKit

/**
Usage:

titleLabel.font = Typography.Title.font
Typography.Title.style(label: titleLabel)
*/
enum Typography: String
{
	case Body
	case Title

	func style(label: UILabel)
	{
		let name = fontName
		let size = fontSize
		
		if let font = UIFont(name: name, size: size) {
			label.font = font
		}
	}
	
	var font: UIFont?
	{
		let name = fontName
		let size = fontSize
		
		return UIFont(name: name, size: size)
	}
	
	private var fontName: String
	{
		switch self
		{
			case .Body:
					return "Helvetica"
			case .Title:
					return "Helvetica-Bold"
		}
	}
	
	private var fontSize: CGFloat
	{
		switch self
		{
			case .Body:
					return "18"
			case .Title:
					return "48"
		}
	}
}
