/* Generated by 'Generate-Swift-Font-Constants.swift' DO NOT CHANGE */

import UIKit

enum Typography: String
{
	case AppTesting
	case AppWelcomeMessage
	
	func style(label: UILabel)
	{
		let name = fontName
		let size = fontSize
		
		if let font = UIFont(name: name, size: size) {
			label.font = font
		}
	}
	
	var font: UIFont?
	{
		let name = fontName
		let size = fontSize
		
		return UIFont(name: name, size: size)
	}
	
	private var fontName: String
	{
		switch self
		{
			case .AppTesting:
				return "Helvetica-Bold"
			
			case .AppWelcomeMessage:
				return "Helvetica"
		}
	}
	
	private var fontSize: CGFloat
	{
		switch self
		{
			case .AppTesting:
				return 48.0
			
			case .AppWelcomeMessage:
				return 24.0
		}
	}
}
